## GameState.gd — Autoload singleton
## Active Ecosystem Simulator engine.
##
## Tick order each frame:
##   1. Advance world clock + day counter + season transitions.
##   2. Consumption pass  — predators hunt prey, reducing prey populations.
##   3. Starvation update — predators that can't eat accumulate starvation days.
##   4. Natural death     — all species age; starvation accelerates predator deaths.
##   5. Procreation       — births, season-modulated, carrying-capacity gated.
##   6. Flush accumulators — apply fractional pop changes to integer populations.
##   7. Resource production — Biomass / DNA / Mutagens; starvation gates output.
extends Node

# ── Signals ───────────────────────────────────────────────────────────────────

signal resources_changed
signal time_changed(hour: float, is_day: bool)
signal day_changed(day: int, season_name: String)
## Emitted in tick step 6 whenever a species gains at least one new individual.
## TerrariumManager listens to this to spawn DNA orbs.
signal procreation_occurred(species_id: String)
signal extinction_triggered(type: int)

enum ExtinctionType { METEOR = 0, ICE_AGE = 1, PANDEMIC = 2, SOLAR_FLARE = 3 }

# ── World clock ───────────────────────────────────────────────────────────────

## In-game hours advanced per real second (0.05 → 1 day ≈ 8 min real time).
const TIME_SPEED: float = 0.05

## Player-controlled simulation multiplier. 1.0 = normal, 1.25x, 1.5x.
## Not saved — always resets to 1x on launch.
var game_speed: float = 1.0

var time_of_day:     float = 6.0
var is_day:          bool  = true
var daylight_factor: float = 1.0

# ── Seasons ────────────────────────────────────────────────────────────────────

enum Season { SPRING = 0, SUMMER = 1, AUTUMN = 2, WINTER = 3 }

## In-game days each season lasts before rotating.
const DAYS_PER_SEASON: int = 7

var current_day:    int    = 0
var current_season: int    = Season.SPRING   ## int because GDScript enum can't be typed in Dicts

# ── Ecosystem limits ───────────────────────────────────────────────────────────

## Maximum combined population across ALL species. Halts T0/T1 procreation
## when reached; forces the player to balance the food web deliberately.
const GLOBAL_TERRITORY_CAP: int = 5000

# ── Sun-energy purchase costs ──────────────────────────────────────────────────
## Flat base costs in Sun Energy units (each sun ray = 10 energy).
## Designed for a click-based economy: T0 affordable early, T2 needs real effort.
const _SUN_COSTS: Dictionary = {
	# Flora — Temperate Forest
	"tall_grass": 2.0, "fern": 3.0, "berry_bush": 10.0, "oak_tree": 25.0,
	# Herbivores
	"mouse": 5.0, "rabbit": 8.0, "squirrel": 8.0, "deer": 15.0,
	# Predators
	"wolf": 15.0, "red_fox": 15.0, "owl": 15.0,
}

## Low DNA costs to unlock T2 predators via collected orbs.
const _RESEARCH_COSTS: Dictionary = {
	"wolf": 100.0, "red_fox": 80.0, "owl": 80.0,
}

# ── Resources ─────────────────────────────────────────────────────────────────

var biomass:    BigNumber
var dna:        BigNumber
var mutagens:   BigNumber   ## Generated by T2; survives Extinction; multiplied on reset.
var sun_energy: BigNumber   ## Primary purchase currency — earned by clicking sun rays.

var click_power: BigNumber

# ── Ecosystem state ────────────────────────────────────────────────────────────

## { species_id: int } — integer population counts.
var populations: Dictionary = {}

## Floating-point pool of available food biomass in the ecosystem.
## T0 flora continuously fills it; T1 herbivores drain it.
## Capped to prevent infinite accumulation.
var environmental_biomass: float = 0.0
const ENV_BIOMASS_CAP: float = 50000.0

var species_catalog:  Dictionary         = {}
var sorted_species:   Array[SpeciesData] = []
var discovered_species: Dictionary       = {}

# ── Permanent multipliers (rogue-lite) ────────────────────────────────────────

var permanent_multipliers: Dictionary = {
	"biomass_production":  1.0,
	"dna_production":      1.0,
	"mutagens_production": 1.0,
	"click_power":         1.0,
	"offline_multiplier":  1.0,
}

# ── Genetic traits ─────────────────────────────────────────────────────────────

## IDs of purchased GeneticTraits — survive Extinction.
var unlocked_traits: Array = []
var _trait_catalog:  Dictionary = {}

# ── Run statistics ─────────────────────────────────────────────────────────────

var run_start_time:       float = 0.0
var highest_tier_reached: int   = 0

# ── Private simulation state ───────────────────────────────────────────────────

## Fractional population changes accumulated between whole-number application.
## Positive = births or recovered prey; negative = deaths or consumed prey.
var _pop_accumulators:   Dictionary = {}   # { species_id: float }

## Days a predator has gone without sufficient food.
## > 0.5 → production penalty; > 2.0 → starvation deaths.
var _starvation_counters: Dictionary = {}  # { species_id: float }

## Sub-day accumulator for advancing current_day.
var _day_accumulator: float = 0.0

var _ui_timer:      float = 0.0
const _UI_INTERVAL: float = 0.1


# ── Lifecycle ──────────────────────────────────────────────────────────────────

func _ready() -> void:
	mutagens   = BigNumber.zero()
	sun_energy = BigNumber.zero()
	_load_species_catalog()
	_load_trait_catalog()
	_reset_resources()
	run_start_time = Time.get_unix_time_from_system()


func _process(delta: float) -> void:
	# Advance world clock — scaled by player's chosen game speed.
	var scaled_delta: float = delta * game_speed
	time_of_day += TIME_SPEED * scaled_delta
	if time_of_day >= 24.0:
		time_of_day -= 24.0
	is_day          = time_of_day >= 6.0 and time_of_day < 18.0
	daylight_factor = _compute_daylight_factor(time_of_day)

	_tick(scaled_delta)

	_ui_timer += delta
	if _ui_timer >= _UI_INTERVAL:
		_ui_timer = 0.0
		resources_changed.emit()
		time_changed.emit(time_of_day, is_day)


# ── Public API ─────────────────────────────────────────────────────────────────

func get_resource(key: String) -> BigNumber:
	match key:
		"biomass":    return biomass
		"dna":        return dna
		"mutagens":   return mutagens
		"sun_energy": return sun_energy
	return BigNumber.zero()


func can_afford(resource: String, amount: BigNumber) -> bool:
	return get_resource(resource).greater_than_or_equal(amount)


func click() -> BigNumber:
	var gained := click_power.multiply_float(permanent_multipliers["click_power"])
	biomass = biomass.add(gained)
	resources_changed.emit()
	return gained


## Release one unit of a species into the ecosystem. Costs Sun Energy.
func buy_species(species_id: String) -> bool:
	var data: SpeciesData = species_catalog.get(species_id)
	if not data or not is_species_discovered(data):
		return false
	var owned: int = populations.get(species_id, 0)
	var cost  := get_buy_cost(species_id)
	if not can_afford("sun_energy", cost):
		return false
	_spend("sun_energy", cost)
	populations[species_id] = owned + 1
	if data.tier > highest_tier_reached:
		highest_tier_reached = data.tier
	resources_changed.emit()
	return true


## Spend DNA to research (discover) a T2 predator species.
func unlock_species(species_id: String) -> bool:
	var data: SpeciesData = species_catalog.get(species_id)
	if not data or is_species_discovered(data):
		return data != null
	var cost := _get_research_cost(species_id)
	if not can_afford("dna", cost):
		return false
	_spend("dna", cost)
	discovered_species[species_id] = true
	resources_changed.emit()
	return true


## Spend Mutagens to permanently unlock a genetic trait.
func unlock_genetic_trait(trait_id: String) -> bool:
	var gt: GeneticTrait = _trait_catalog.get(trait_id)
	if not gt:
		return false
	if trait_id in unlocked_traits:
		return true
	var cost := BigNumber.from_float(gt.mutagen_cost)
	if not can_afford("mutagens", cost):
		return false
	_spend("mutagens", cost)
	unlocked_traits.append(trait_id)
	resources_changed.emit()
	return true


func is_species_discovered(data: SpeciesData) -> bool:
	# T0 flora and T1 herbivores are always visible — no research needed.
	# T2 predators must be unlocked with DNA orbs.
	if data.tier <= 1:
		return true
	return data.is_discovered or discovered_species.get(data.id, false)


func get_population(species_id: String) -> int:
	return populations.get(species_id, 0)


func get_total_population() -> int:
	return _total_population()


## True when the predator's starvation counter exceeds 0.5 in-game days.
func is_species_starving(species_id: String) -> bool:
	return _starvation_counters.get(species_id, 0.0) > 0.5


## Starvation counter in in-game days for UI display.
func get_starvation_days(species_id: String) -> float:
	return _starvation_counters.get(species_id, 0.0)


## Sun-energy cost to buy the next unit of a species (scales with owned count).
func get_buy_cost(species_id: String) -> BigNumber:
	var data: SpeciesData = species_catalog.get(species_id)
	if not data:
		return BigNumber.zero()
	var base: float  = _SUN_COSTS.get(species_id, 50.0)
	var owned: int   = populations.get(species_id, 0)
	var cost: float  = base if owned == 0 else base * pow(data.cost_scaling, float(owned))
	return BigNumber.from_float(maxf(1.0, roundf(cost)))


## Add sun energy directly (called by SunManager when a ray is collected).
func add_sun_energy(amount: float) -> void:
	sun_energy = sun_energy.add(BigNumber.from_float(amount))
	resources_changed.emit()


## Add DNA directly (called by DNAOrb when collected).
func add_dna(amount: float) -> void:
	dna = dna.add(BigNumber.from_float(amount))
	resources_changed.emit()


func is_ecosystem_balanced() -> bool:
	var p0: int = get_total_population_by_tier(0)
	var p1: int = get_total_population_by_tier(1)
	var p2: int = get_total_population_by_tier(2)
	if p0 <= 0:
		return false
	var safe_herb: int = int(float(p0) / 3.33)
	var safe_pred: int = int(float(p1) / 3.0)
	return p1 <= safe_herb and p2 <= safe_pred


## Total live population for a given tier — used by BalanceMeter.
func get_total_population_by_tier(tier: int) -> int:
	var total: int = 0
	for id: String in populations:
		var data: SpeciesData = species_catalog.get(id)
		if data and data.tier == tier:
			total += populations.get(id, 0)
	return total


func get_species_time_modifier(data: SpeciesData) -> float:
	return lerpf(data.night_efficiency, data.day_efficiency, daylight_factor)


## Net production rate for a resource. Used by HUD for live display.
## Does not account for stochastic births/deaths/compost.
func get_net_per_second(resource: String) -> BigNumber:
	var produced := BigNumber.zero()
	var consumed := BigNumber.zero()
	for id: String in populations:
		var count: int = populations[id]
		if count <= 0:
			continue
		var data: SpeciesData = species_catalog.get(id)
		if not data:
			continue
		var starvation: float = _starvation_counters.get(id, 0.0)
		var prod_penalty: float = _production_penalty(starvation)
		var count_bn  := BigNumber.from_int(count)
		var time_mod  := get_species_time_modifier(data)
		var season_prod := _season_production_mult(data)
		var eff_mod   : float = time_mod * season_prod * prod_penalty
		match resource:
			"biomass":
				var mult: float = permanent_multipliers["biomass_production"]
				produced = produced.add(
					data.get_biomass_produced_per_second().multiply(count_bn).multiply_float(eff_mod * mult)
				)
				consumed = consumed.add(
					data.get_biomass_consumed_per_second().multiply(count_bn)
				)
			"dna":
				var mult: float = permanent_multipliers["dna_production"]
				produced = produced.add(
					data.get_dna_produced_per_second().multiply(count_bn).multiply_float(eff_mod * mult)
				)
			"mutagens":
				var mult: float = permanent_multipliers["mutagens_production"]
				produced = produced.add(
					data.get_mutagens_produced_per_second().multiply(count_bn).multiply_float(eff_mod * mult)
				)
	return produced.subtract(consumed)


## Signed float net biomass rate for HUD display.
## Negative when herbivore consumption exceeds flora production.
func get_biomass_net_rate() -> float:
	var produced: float = 0.0
	var consumed: float = 0.0
	for id: String in populations:
		var count: int = populations.get(id, 0)
		if count <= 0:
			continue
		var data: SpeciesData = species_catalog.get(id)
		if not data:
			continue
		var starvation: float   = _starvation_counters.get(id, 0.0)
		var prod_penalty: float = _production_penalty(starvation)
		var time_mod: float     = get_species_time_modifier(data)
		var season_prod: float  = _season_production_mult(data)
		var trait_prod: float   = _apply_trait_modifier(data, "production_mult", 1.0)
		if current_season == Season.WINTER:
			trait_prod *= _apply_trait_modifier(data, "winter_production_mult", 1.0)
		var eff_mod: float = time_mod * season_prod * prod_penalty * trait_prod
		var bm_mult: float = permanent_multipliers["biomass_production"]
		produced += data.produces_biomass * float(count) * eff_mod * bm_mult
		consumed += data.consumes_biomass * float(count)
	return produced - consumed


func get_time_string() -> String:
	var h := int(time_of_day)
	var m := int(fmod(time_of_day, 1.0) * 60.0)
	return "%02d:%02d" % [h, m]


func get_period_name() -> String:
	if time_of_day >= 5.0 and time_of_day < 7.0:   return "DAWN"
	elif time_of_day >= 7.0 and time_of_day < 17.0: return "DAY"
	elif time_of_day >= 17.0 and time_of_day < 19.0: return "DUSK"
	else:                                             return "NIGHT"


func get_season_name() -> String:
	match current_season:
		Season.SPRING: return "SPRING"
		Season.SUMMER: return "SUMMER"
		Season.AUTUMN: return "AUTUMN"
		Season.WINTER: return "WINTER"
	return "SPRING"


## Trigger an Extinction event of the given type.
## Returns the Mutagen multiplier applied.
func trigger_extinction(type: int = ExtinctionType.METEOR) -> float:
	var bonus: float
	match type:
		ExtinctionType.METEOR:
			bonus = 1.0 + (0.5 * float(highest_tier_reached))
			mutagens = mutagens.multiply_float(bonus)
			_reset_resources()
		ExtinctionType.ICE_AGE:
			bonus = 0.8 + (0.3 * float(highest_tier_reached))
			mutagens = mutagens.multiply_float(bonus)
			_partial_extinction(0.95, 0.70, 0.40)
			sun_energy = sun_energy.multiply_float(0.5)
			environmental_biomass = 50.0
		ExtinctionType.PANDEMIC:
			bonus = 0.5 + (0.2 * float(highest_tier_reached))
			mutagens = mutagens.multiply_float(bonus)
			_partial_extinction(0.30, 0.85, 0.20)
			sun_energy = sun_energy.multiply_float(0.7)
		ExtinctionType.SOLAR_FLARE:
			bonus = 0.4 + (0.15 * float(highest_tier_reached))
			mutagens = mutagens.multiply_float(bonus)
			_partial_extinction(0.90, 0.20, 0.10)
			sun_energy = sun_energy.multiply_float(0.6)
			environmental_biomass = 20.0
		_:
			bonus = 1.0
	run_start_time       = Time.get_unix_time_from_system()
	highest_tier_reached = 0
	current_day          = 0
	current_season       = Season.SPRING
	_day_accumulator     = 0.0
	_starvation_counters.clear()
	_pop_accumulators.clear()
	extinction_triggered.emit(type)
	resources_changed.emit()
	return bonus


## Apply offline simulation. Hard-capped at 2 in-game days to prevent
## ecosystem collapse (e.g. wolves eating all deer while player is away).
func apply_offline_progress(elapsed_seconds: float) -> void:
	# 2 in-game days in real seconds at current TIME_SPEED.
	var max_real_seconds: float = (48.0 / TIME_SPEED)
	var effective: float = minf(
		elapsed_seconds * permanent_multipliers["offline_multiplier"],
		max_real_seconds
	)
	if effective > 0.0:
		_tick(effective)
	time_of_day     = fmod(time_of_day + TIME_SPEED * effective, 24.0)
	is_day          = time_of_day >= 6.0 and time_of_day < 18.0
	daylight_factor = _compute_daylight_factor(time_of_day)


# ── Main simulation tick ───────────────────────────────────────────────────────

func _tick(delta: float) -> void:
	## delta is in REAL seconds. Convert to in-game days throughout.
	var delta_days: float = delta * TIME_SPEED / 24.0

	# ── 1. Advance day counter and seasons ────────────────────────────────────
	_day_accumulator += delta_days
	while _day_accumulator >= 1.0:
		_day_accumulator -= 1.0
		current_day += 1
		_check_season_transition()

	# ── 2. Carrying capacity snapshot ─────────────────────────────────────────
	var total_pop:   int  = _total_population()
	var at_t01_cap:  bool = total_pop >= GLOBAL_TERRITORY_CAP

	# ── 3. Consumption pass — predators actively hunt prey ────────────────────
	# Each predator species eats a fraction of its prey population each tick.
	# Prey is removed via _pop_accumulators (applied to populations in step 6).
	for pred_id: String in populations:
		var pred_count: int = populations.get(pred_id, 0)
		if pred_count <= 0:
			continue
		var data: SpeciesData = species_catalog.get(pred_id)
		if not data or data.prey_consumption_rate.is_empty():
			continue

		var time_mod:        float = get_species_time_modifier(data)
		var best_fed_ratio: float = 0.0

		for prey_id: String in data.prey_consumption_rate:
			var rate: float    = float(data.prey_consumption_rate[prey_id])
			var desired: float = float(pred_count) * rate * time_mod * delta_days
			if desired <= 0.0:
				continue
			# Available = current integer pop + accumulated fractional buffer
			var available: float = float(populations.get(prey_id, 0)) \
				+ _pop_accumulators.get(prey_id, 0.0)
			var consumed: float  = minf(desired, maxf(0.0, available))
			_pop_accumulators[prey_id] = _pop_accumulators.get(prey_id, 0.0) - consumed
			var single_ratio: float = consumed / desired if desired > 0.0 else 1.0
			if single_ratio > best_fed_ratio:
				best_fed_ratio = single_ratio

		# A species is well-fed if ANY single prey source satisfies its hunger.
		# Using the best single-prey ratio prevents false starvation when one food
		# source is plentiful but other preferred prey are absent.
		var avg_fed: float = best_fed_ratio
		if avg_fed >= 0.8:
			# Well fed — gradually recover starvation.
			_starvation_counters[pred_id] = maxf(
				0.0, _starvation_counters.get(pred_id, 0.0) - delta_days
			)
		else:
			# Hungry — accumulate starvation proportionally to shortfall.
			_starvation_counters[pred_id] = \
				_starvation_counters.get(pred_id, 0.0) + delta_days * (1.0 - avg_fed)

	# ── 4. Natural death pass ──────────────────────────────────────────────────
	for species_id: String in populations:
		var count: int = populations.get(species_id, 0)
		if count <= 0:
			continue
		var data: SpeciesData = species_catalog.get(species_id)
		if not data or data.base_lifespan_days <= 0.0:
			continue

		# Apply GeneticTrait lifespan multiplier.
		var eff_lifespan: float = _apply_trait_modifier(data, "lifespan_mult", data.base_lifespan_days)
		var deaths: float = float(count) * delta_days / eff_lifespan
		_pop_accumulators[species_id] = _pop_accumulators.get(species_id, 0.0) - deaths

		# Starvation accelerates predator deaths beyond 2 starvation-days.
		var starvation: float = _starvation_counters.get(species_id, 0.0)
		if starvation > 2.0:
			var starvation_deaths: float = float(count) * delta_days * (starvation - 2.0) * 0.5
			_pop_accumulators[species_id] -= starvation_deaths

	# ── 5. Procreation pass ────────────────────────────────────────────────────
	for species_id: String in populations:
		var count: int = populations.get(species_id, 0)
		if count <= 0:
			continue
		var data: SpeciesData = species_catalog.get(species_id)
		if not data or data.procreation_chance <= 0.0:
			continue

		# Carrying cap halts T0 and T1 procreation.
		if at_t01_cap and data.tier <= 1:
			continue

		var season_mult: float = _season_procreation_mult(data)
		if season_mult <= 0.0:
			continue

		# Starvation reduces procreation when half-fed or worse.
		var starvation: float = _starvation_counters.get(species_id, 0.0)
		var hunger_mult: float = 1.0
		if starvation > 1.0:
			hunger_mult = 0.0
		elif starvation > 0.5:
			hunger_mult = 1.0 - ((starvation - 0.5) / 0.5)

		# Apply GeneticTrait procreation multiplier.
		var eff_proc: float = _apply_trait_modifier(
			data, "procreation_mult",
			data.procreation_chance * season_mult * hunger_mult
		)
		# Winter-specific trait bonus.
		if current_season == Season.WINTER:
			eff_proc = _apply_trait_modifier(data, "winter_procreation_mult", eff_proc)

		var eff_litter: float = float(data.litter_size) + \
			_apply_trait_modifier(data, "litter_bonus", 0.0)

		# Time-of-day modulation: normalised so daily total stays the same,
		# but day-active species visibly breed during the day.
		var avg_eff: float = (data.day_efficiency + data.night_efficiency) * 0.5
		var time_mod: float = get_species_time_modifier(data)
		var norm_time: float = time_mod / maxf(0.01, avg_eff)
		var births: float = float(count) * eff_proc * delta_days * eff_litter * norm_time

		# Soft-clamp births to avoid bursting past the territory cap (T0/T1).
		if data.tier <= 1:
			var remaining_slots: float = float(GLOBAL_TERRITORY_CAP - total_pop)
			births = minf(births, maxf(0.0, remaining_slots))

		_pop_accumulators[species_id] = _pop_accumulators.get(species_id, 0.0) + births

	# ── 6. Flush accumulators — apply to integer populations ──────────────────
	var compost_gained: float = 0.0
	for species_id: String in _pop_accumulators.keys():
		var delta_pop: float = _pop_accumulators[species_id]
		var int_change: int  = int(floor(delta_pop))
		if int_change == 0:
			continue
		var old_pop: int = populations.get(species_id, 0)
		var new_pop: int = maxi(0, old_pop + int_change)
		populations[species_id] = new_pop
		_pop_accumulators[species_id] = delta_pop - float(int_change)
		# Births → notify TerrariumManager so it can spawn a DNA orb nearby.
		if int_change > 0:
			procreation_occurred.emit(species_id)
		# Any net population loss generates compost Biomass.
		var actual_loss: int = old_pop - new_pop
		if actual_loss > 0:
			var data: SpeciesData = species_catalog.get(species_id)
			if data:
				var eff_compost: float = _apply_trait_modifier(
					data, "compost_mult", data.compost_value
				)
				compost_gained += float(actual_loss) * eff_compost

	if compost_gained > 0.0:
		biomass = biomass.add(BigNumber.from_float(compost_gained))

	# ── 7a. Producer Pass — T0 flora fills the environmental biomass pool ────────
	# Each flora species converts its produces_biomass rate into the shared pool.
	# Pool is capped at ENV_BIOMASS_CAP to prevent infinite accumulation.
	for species_id: String in populations:
		var count: int = populations.get(species_id, 0)
		if count <= 0:
			continue
		var data: SpeciesData = species_catalog.get(species_id)
		if not data or data.tier != 0 or data.produces_biomass <= 0.0:
			continue
		var time_mod: float    = get_species_time_modifier(data)
		var season_prod: float = _season_production_mult(data)
		var bm_mult: float     = permanent_multipliers["biomass_production"]
		var trait_prod: float  = _apply_trait_modifier(data, "production_mult", 1.0)
		if current_season == Season.WINTER:
			trait_prod *= _apply_trait_modifier(data, "winter_production_mult", 1.0)
		var eff_mod: float  = time_mod * season_prod * trait_prod
		var produced: float = data.produces_biomass * float(count) * delta * eff_mod * bm_mult
		environmental_biomass = minf(environmental_biomass + produced, ENV_BIOMASS_CAP)

	# ── 7b. Herbivore Pass — T1 herbivores eat from environmental_biomass ────────
	# All herbivore demand is totalled; if the pool is short, every species
	# starves proportionally (fair ration — no first-come advantage).
	var herb_desired: Dictionary = {}
	var total_desired: float     = 0.0
	for species_id: String in populations:
		var count: int = populations.get(species_id, 0)
		if count <= 0:
			continue
		var data: SpeciesData = species_catalog.get(species_id)
		if not data or data.consumes_biomass <= 0.0:
			continue
		var owed: float = data.consumes_biomass * float(count) * delta
		herb_desired[species_id] = owed
		total_desired += owed

	if total_desired > 0.0:
		var fed_ratio: float      = minf(1.0, environmental_biomass / total_desired)
		var actual_consumed: float = minf(environmental_biomass, total_desired)
		environmental_biomass      = maxf(0.0, environmental_biomass - actual_consumed)
		for herb_id: String in herb_desired:
			if fed_ratio >= 0.8:
				_starvation_counters[herb_id] = maxf(
					0.0, _starvation_counters.get(herb_id, 0.0) - delta_days
				)
			else:
				_starvation_counters[herb_id] = \
					_starvation_counters.get(herb_id, 0.0) + delta_days * (1.0 - fed_ratio)

	# ── 7c. Mutagen production — T2 predators generate Mutagens passively ────────
	# DNA comes from clicking procreation orbs only (passive line intentionally off).
	var m_delta := BigNumber.zero()
	for species_id: String in populations:
		var count: int = populations.get(species_id, 0)
		if count <= 0:
			continue
		var data: SpeciesData = species_catalog.get(species_id)
		if not data or data.tier != 2:
			continue
		var starvation: float   = _starvation_counters.get(species_id, 0.0)
		var prod_penalty: float = _production_penalty(starvation)
		var count_bn            := BigNumber.from_int(count)
		var time_mod: float     = get_species_time_modifier(data)
		var season_prod: float  = _season_production_mult(data)
		var mut_mult: float     = permanent_multipliers["mutagens_production"]
		var trait_prod: float   = _apply_trait_modifier(data, "production_mult", 1.0)
		if current_season == Season.WINTER:
			trait_prod *= _apply_trait_modifier(data, "winter_production_mult", 1.0)
		var eff_mod: float = time_mod * season_prod * prod_penalty * trait_prod
		m_delta = m_delta.add(
			data.get_mutagens_produced_per_second().multiply(count_bn).multiply_float(delta * eff_mod * mut_mult)
		)
	mutagens = mutagens.add(m_delta)

	# ── 8. Track highest tier reached ─────────────────────────────────────────
	for species_id: String in populations:
		if populations.get(species_id, 0) > 0:
			var data: SpeciesData = species_catalog.get(species_id)
			if data and data.tier > highest_tier_reached:
				highest_tier_reached = data.tier


# ── Helpers ────────────────────────────────────────────────────────────────────

## 0.0 → 1.0 daylight factor with 2-hour dawn/dusk ramps.
func _compute_daylight_factor(hour: float) -> float:
	if hour >= 7.0 and hour < 17.0:
		return 1.0
	elif hour >= 5.0 and hour < 7.0:
		return (hour - 5.0) / 2.0
	elif hour >= 17.0 and hour < 19.0:
		return 1.0 - (hour - 17.0) / 2.0
	else:
		return 0.0


## Check whether current_day has crossed a season boundary.
func _check_season_transition() -> void:
	@warning_ignore("integer_division")
	var new_season: int = (current_day / DAYS_PER_SEASON) % 4
	if new_season != current_season:
		current_season = new_season
		day_changed.emit(current_day, get_season_name())
	else:
		day_changed.emit(current_day, get_season_name())


## Season multiplier applied to procreation_chance.
##   SPRING → × 1.5   SUMMER → × 1.0   AUTUMN → × 0.7   WINTER → depends on tier
func _season_procreation_mult(data: SpeciesData) -> float:
	match current_season:
		Season.SPRING: return 1.5
		Season.SUMMER: return 1.0
		Season.AUTUMN: return 0.7
		Season.WINTER:
			if data.tier == 0:
				return 0.0   # Flora does not reproduce in winter.
			return 0.3       # Animals reproduce slowly in winter.
	return 1.0


## Season multiplier applied to resource production rates.
##   WINTER halves flora Biomass production (dormant, not dead).
func _season_production_mult(data: SpeciesData) -> float:
	if current_season == Season.WINTER and data.tier == 0:
		return 0.2
	return 1.0


## Maps starvation days to a [0.0 – 1.0] production multiplier.
## Penalty begins at 0.5 starvation-days; production reaches 0 at 2.5 days.
func _production_penalty(starvation_days: float) -> float:
	if starvation_days <= 0.5:
		return 1.0
	return maxf(0.0, 1.0 - ((starvation_days - 0.5) / 2.0))


## Apply a GeneticTrait modifier of the given type to base_value.
## Respects species_target and tier_target filters on each trait.
func _apply_trait_modifier(data: SpeciesData, effect_type: String, base_value: float) -> float:
	var result: float = base_value
	for trait_id: String in unlocked_traits:
		var gt: GeneticTrait = _trait_catalog.get(trait_id)
		if not gt or gt.effect_type != effect_type:
			continue
		# Species-specific filter.
		if not gt.species_target.is_empty() and gt.species_target != data.id:
			continue
		# Tier filter (only when species_target is not set).
		if gt.species_target.is_empty() and gt.tier_target >= 0 \
				and gt.tier_target != data.tier:
			continue
		match gt.modifier_type:
			"multiply": result *= gt.effect_value
			"add":      result += gt.effect_value
	return result


## Reduce populations by tier without full reset.
## kill_rate is 0.0 (no kill) -> 1.0 (total wipe).
func _partial_extinction(t0_kill: float, t1_kill: float, t2_kill: float) -> void:
	for species_id: String in populations:
		var data: SpeciesData = species_catalog.get(species_id)
		if not data:
			continue
		var kill_rate: float = 0.0
		match data.tier:
			0: kill_rate = t0_kill
			1: kill_rate = t1_kill
			2: kill_rate = t2_kill
		var current: int = populations.get(species_id, 0)
		populations[species_id] = maxi(0, int(float(current) * (1.0 - kill_rate)))


func _total_population() -> int:
	var total: int = 0
	for id: String in populations:
		total += populations.get(id, 0)
	return total


func _spend(resource: String, amount: BigNumber) -> void:
	match resource:
		"biomass":    biomass    = biomass.subtract(amount)
		"dna":        dna        = dna.subtract(amount)
		"mutagens":   mutagens   = mutagens.subtract(amount)
		"sun_energy": sun_energy = sun_energy.subtract(amount)


## Returns the DNA research cost for a T2 predator (overrides .tres values).
func _get_research_cost(species_id: String) -> BigNumber:
	var cost: float = _RESEARCH_COSTS.get(species_id, 0.0)
	return BigNumber.from_float(cost) if cost > 0.0 else BigNumber.zero()


func _reset_resources() -> void:
	biomass               = BigNumber.new(1.0, 1)   # 10 Biomass to start.
	dna                   = BigNumber.zero()
	sun_energy            = BigNumber.from_float(50.0)   # Seed the player with a little energy.
	click_power           = BigNumber.new(1.0, 0)
	environmental_biomass = 100.0   # Small seed pool so early herbivores don't starve instantly.
	populations           = {}
	_pop_accumulators.clear()
	# mutagens, discovered_species, unlocked_traits survive Extinction.


func _load_species_catalog() -> void:
	sorted_species.clear()
	species_catalog.clear()
	var dir := DirAccess.open("res://data/species/")
	if not dir:
		push_error("GameState: could not open res://data/species/")
		return
	dir.list_dir_begin()
	var fname := dir.get_next()
	while fname != "":
		if fname.ends_with(".tres") and not fname.begins_with("."):
			var data := load("res://data/species/" + fname) as SpeciesData
			if data and data.id != "":
				species_catalog[data.id] = data
				sorted_species.append(data)
		fname = dir.get_next()
	dir.list_dir_end()
	sorted_species.sort_custom(func(a: SpeciesData, b: SpeciesData) -> bool:
		if a.tier != b.tier: return a.tier < b.tier
		if a.base_cost_exponent != b.base_cost_exponent:
			return a.base_cost_exponent < b.base_cost_exponent
		return a.base_cost_mantissa < b.base_cost_mantissa
	)


func _load_trait_catalog() -> void:
	_trait_catalog.clear()
	var dir := DirAccess.open("res://data/traits/")
	if not dir:
		return   # Trait folder is optional; no error if absent.
	dir.list_dir_begin()
	var fname := dir.get_next()
	while fname != "":
		if fname.ends_with(".tres") and not fname.begins_with("."):
			var gt := load("res://data/traits/" + fname) as GeneticTrait
			if gt and gt.id != "":
				_trait_catalog[gt.id] = gt
		fname = dir.get_next()
	dir.list_dir_end()
